[package]
name = "elf_sub"
version = "0.1.0"
edition = "2021"
readme = "README.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
