[package]
name = "sub_pilot"
version = "0.1.0"
edition = "2021"
readme = "README.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
